<div class="container">       
				
                
<h1 class="text-center top-space">Partners</h1>

                 
                <div class="post-entry">
                    <p>Science Gateways are online user interfaces and services that support Web-based science through the execution of online computational experiments and the management of data. &nbsp;The SciGaP team is composed of prominent Science Gateway developers and deliverers. We collaborate with many other groups within the Science Gateway community. To learn more, see the links below.</p>
<p><a title="Apache Airavata" href="http://airavata.apache.org/" target="_blank">Apache Airavata</a>: Airavata is open source software to power the job and workflow management used by Science Gateways.</p>
<p><a title="CIPRES" href="http://www.phylo.org/" target="_blank">CIPRES Science Gateway</a>: CIPRES is a popular Science Gateway for conducting online research into&nbsp;phylogenetics using supercomputers managed by the <a href="https://www.xsede.org" target="_blank">NSF XSEDE</a> project. &nbsp;Mark Miller is the CIPRES gateway’s project leader, and Terri Schwartz is the lead developer.</p>
<p><a title="NSG Portal" href="http://www.nsgportal.org/" target="_blank">Neuroscience Gatewa</a>y: NSG is a Science Gateway that provides a Web interface to XSEDE supercomputing resources for the neuroscience community. Amit Majumdar is the project leader for the NSG, Subhashini Sivagnanam and Kenneth Yoshimoto are&nbsp;the lead developers.</p>
<p><a href="http://www.opensciencegrid.org/" target="_blank">Open Science Grid:</a>&nbsp;The OSG is a voluntary federation of academic computing systems that supports high throughput computing.</p>
<p><a href="http://www.prace-ri.eu/" target="_blank">PRACE</a>: &nbsp;PRACE is the European Union’s federated high performance computing infrastructure. &nbsp;PRACE in the EU and XSEDE in the US are roughly similar.</p>
<p><a title="SDSC" href="http://www.sdsc.edu/" target="_blank">San Diego Supercomputing Center</a>: SDSC is an XSEDE partner and home to the CIPRES and NSG science gateways. &nbsp;It operates the Trestles and Gordon supercomputers.</p>
<p><a href="http://sgrc.iu.edu" target="_blank">SGRC @ IU</a>: The IU Science Gateway Group develops software, participates in the Apache Software Foundation, and provides consulting support on the development and operation of Science Gateways. &nbsp;Marlon Pierce leads the group and Suresh Marru is the group’s principal software architect.</p>
<p><a title="SGW-I" href="http://sciencegateways.org/" target="_blank">Science Gateway Institute</a>: Nancy Wilkins-Diehr at SDSC leads this NSF&nbsp;<a href="http://www.nsf.gov/pubs/2013/nsf13511/nsf13511.htm" target="_blank">Software Infrastructure for Sustained Innovation</a> conceptualization award that includes members of the HUBzero, iPlant, and SciGaP Science Gateway projects. &nbsp;The institute’s ultimate goal is to foster the Science Gateway community through a range of services, including incubator support, consultation services, gateway frameworks, community forums, and workflow development.</p>
<p><a title="UltraScan" href="http://www.ultrascan.uthscsa.edu/" target="_blank">UltraScan Science Gateway</a>: &nbsp;UltraScan is a comprehensive gateway for the&nbsp;high-resolution analysis of hydrodynamic data using remote supercomputing&nbsp;resources. The Gateway has been in existence since 2004 and was one&nbsp;of the first adopters of the Apache Airavata middleware infrastructure. It&nbsp;is connected to XSEDE supercomputers in SDSC, TACC, local resources at the&nbsp;University of Texas Health Science Center in San Antonio, and at the&nbsp;Jülich Supercomputing Center in Germany, it serves a worldwide user base&nbsp;with high-performance computing resources for biophysical, molecular&nbsp;biology, biomedical and material science applications.</p>
<p><a href="https://github.com/SciGaP/workbench-install-example/" target="_blank">Workbench Framework:</a>&nbsp; CIPRES and the Neuroscience Gateway are both based on the Workbench Framework.</p>
<p><a href="https://www.xsede.org/gateways-overview" target="_blank">XSEDE Science Gateways</a>: The NSF XSEDE project integrates access to supercomputer centers across the country. <a href="https://www.xsede.org/ecss" target="_blank">Extended Collaborative Support Services (ECSS)</a> are a major component of XSEDE, allocating time of &nbsp;XSEDE staff members to work collaboratively with academic researchers. Within ECSS, the Science Gateway program provides experienced staff members who can help develop new gateways or help port existing gateways to use XSEDE resources. &nbsp;SciGaP encourages researchers needing help with either task to apply for support.</p>
                                    </div><!-- end of .post-entry -->
            
				
     		               
				      
			</div>